### PR TITLE
Installation instructions

### PR DESCRIPTION
**Pull request by Canop**
- for people not willing to fetch the GH repository
- preventing version conflicts with --locked

### CODE REVIEW

**Comment by generic-user1** [comment]
Other than the spelling issues I am a fan of this change. If you can correct those, I will merge this. Thanks!

**Comment by Canop** [comment]
Fixed the typo I found. Can you point the other one(s) ?

**Comment by generic-user1** [comment]
Just the 'intent' vs 'intend' issue. Everything else looks good.

**Comment by generic-user1** [comment]
Thanks for your contribution

**Pull request merged**
